TELEBOT_TOKEN = '768010442:AAHItr6E0TYmNlTiXp2HHIFbV41KnSCS_vk'
MAIN_URL = f'https://api.telegram.org/bot{TELEBOT_TOKEN}'
STICKER_ID = 'CAADAgADggIAAlwohgj91172rg2WVAI'
photo1 = 'templates/Photos/welcome_img.jpg'
photo2 = 'templates/Photos/bars_info.jpg'
photo3 = 'templates/Photos/connect.jpg'
doc1 = 'templates/Docs/Согласие.docx'