# Generated by Django 2.0.3 on 2018-12-26 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField(unique=True)),
                ('specialty', models.CharField(max_length=250)),
                ('programm_language', models.CharField(max_length=250)),
                ('fio', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('study', models.CharField(max_length=250)),
                ('skills', models.TextField(max_length=4096)),
                ('time_work', models.TextField(max_length=4096)),
                ('schedule', models.TextField(max_length=4096)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 26, 22, 23, 1, 961535))),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User')),
            ],
        ),
    ]
