# Generated by Django 2.0.3 on 2018-12-27 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20181226_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 15, 57, 49, 32438)),
        ),
    ]
