# Generated by Django 2.0.3 on 2018-12-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20181227_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 17, 15, 38, 680974)),
        ),
    ]
