# Generated by Django 2.0.3 on 2018-12-27 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20181227_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 17, 19, 57, 158542)),
        ),
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.CharField(blank=True, default='0', max_length=250),
        ),
    ]
