# Generated by Django 2.0.3 on 2018-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20181227_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
