# Generated by Django 2.1.4 on 2018-12-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20181227_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_before_choice', to='bot.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choice', to='bot.Question'),
        ),
    ]
